# Generated by Django 5.1.2 on 2025-11-27 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_answered_by_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_id', models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_api.lead')),
                ('most_recent_project_id', models.ForeignKey(blank=True, db_column='most_recent_project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.project')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_id', models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_api.lead')),
                ('project_id', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.project')),
                ('property_id', models.ForeignKey(blank=True, db_column='property_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.property')),
                ('conversation_id', models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_api.conversation')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('human', 'Human'), ('ai-assistant', 'AI Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('conversation_id', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, to='db_api.conversation')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
