# Generated by Django 5.1.2 on 2025-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0003_alter_message_options_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estado_agentico',
            field=models.TextField(default='ONBOARDING'),
        ),
    ]
