# Generated by Django 5.1.2 on 2025-11-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0004_lead_estado_agentico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estado_agentico',
            field=models.TextField(default='onboarding'),
        ),
    ]
