# Generated by Django 5.1.2 on 2025-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0005_alter_lead_estado_agentico'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='funciones_empleadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
