# Generated by Django 5.1.2 on 2025-11-27 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('brochure_url', models.TextField(blank=True, null=True)),
                ('includes_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('has_showroom', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Typology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('num_bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('num_bathrooms', models.SmallIntegerField(blank=True, null=True)),
                ('area_m2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typologies',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing', models.IntegerField(blank=True, null=True)),
                ('view_type', models.TextField(blank=True, null=True)),
                ('floor_no', models.TextField(blank=True, null=True)),
                ('project_id', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.project')),
                ('typology_id', models.ForeignKey(blank=True, db_column='typology_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.typology')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
    ]
