# Generated by Django 5.1.2 on 2025-11-27 04:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='busqueda',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='busqueda',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='typology',
            name='busqueda',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
